"""Ouroboros tool definitions for MCP server — backward-compatible shim.

All handler classes, factory functions, and OUROBOROS_TOOLS have been moved
to the ``handlers/`` sub-package. This module re-exports every public symbol
so that existing ``from ouroboros.mcp.tools.definitions import X`` imports
continue to work without modification.
"""

from ouroboros.mcp.tools.handlers import (  # noqa: F401
    # Handler classes
    ACDashboardHandler,
    CancelExecutionHandler,
    CancelJobHandler,
    EvaluateHandler,
    EvolveRewindHandler,
    EvolveStepHandler,
    ExecuteSeedHandler,
    GenerateSeedHandler,
    InterviewHandler,
    JobResultHandler,
    JobStatusHandler,
    JobWaitHandler,
    LateralThinkHandler,
    LineageStatusHandler,
    MeasureDriftHandler,
    QueryEventsHandler,
    SessionStatusHandler,
    StartEvolveStepHandler,
    StartExecuteSeedHandler,
    # Factory functions
    cancel_job_handler,
    evaluate_handler,
    evolve_rewind_handler,
    evolve_step_handler,
    execute_seed_handler,
    generate_seed_handler,
    interview_handler,
    job_result_handler,
    job_status_handler,
    job_wait_handler,
    lateral_think_handler,
    lineage_status_handler,
    measure_drift_handler,
    query_events_handler,
    session_status_handler,
    start_evolve_step_handler,
    start_execute_seed_handler,
    # Tool registration tuple
    OUROBOROS_TOOLS,
)

__all__ = [
    "ACDashboardHandler",
    "CancelExecutionHandler",
    "CancelJobHandler",
    "EvaluateHandler",
    "EvolveRewindHandler",
    "EvolveStepHandler",
    "ExecuteSeedHandler",
    "GenerateSeedHandler",
    "InterviewHandler",
    "JobResultHandler",
    "JobStatusHandler",
    "JobWaitHandler",
    "LateralThinkHandler",
    "LineageStatusHandler",
    "MeasureDriftHandler",
    "OUROBOROS_TOOLS",
    "QueryEventsHandler",
    "SessionStatusHandler",
    "StartEvolveStepHandler",
    "StartExecuteSeedHandler",
    "cancel_job_handler",
    "evaluate_handler",
    "evolve_rewind_handler",
    "evolve_step_handler",
    "execute_seed_handler",
    "generate_seed_handler",
    "interview_handler",
    "job_result_handler",
    "job_status_handler",
    "job_wait_handler",
    "lateral_think_handler",
    "lineage_status_handler",
    "measure_drift_handler",
    "query_events_handler",
    "session_status_handler",
    "start_evolve_step_handler",
    "start_execute_seed_handler",
]
